/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FichasMedicas;

import asignaciones.Asignar_Paciente;
import comons.negocio.Paciente;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JhonJimenez
 */
public class PiscologiaEducativa extends javax.swing.JFrame {
    Paciente paciente;
    /**
     * Creates new form PiscologiaClinica
     */
    public PiscologiaEducativa(Paciente paciente) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.paciente = paciente;
        cargarDatosPsicologiaClinica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        txtEspecificarAsignaturas = new javax.swing.JTextField();
        txtCausaCambio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtCDIedad = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtEdadEGB1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCausaPerdida = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtEdadInicial1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtActividadEscolar = new javax.swing.JTextField();
        txtIdPaciente = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtCausaDesercion = new javax.swing.JTextField();
        txtNombrePaciente = new javax.swing.JTextField();
        txtCedulaPaciente = new javax.swing.JTextField();
        txtAsignaturasPreferidas = new javax.swing.JTextField();
        txtAsignaturasDisgustan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEdadInicial2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtIdEspecialista = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtGradoAdaptacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbcdi = new javax.swing.JComboBox<>();
        cbini1 = new javax.swing.JComboBox<>();
        cbini2 = new javax.swing.JComboBox<>();
        cbebg1 = new javax.swing.JComboBox<>();
        cbpdc = new javax.swing.JComboBox<>();
        cbde = new javax.swing.JComboBox<>();
        cbci = new javax.swing.JComboBox<>();
        cbpa = new javax.swing.JComboBox<>();
        cbep = new javax.swing.JComboBox<>();
        cbrt = new javax.swing.JComboBox<>();
        cbag = new javax.swing.JComboBox<>();
        cbrd = new javax.swing.JComboBox<>();
        cbli = new javax.swing.JComboBox<>();
        cbrg = new javax.swing.JComboBox<>();
        cbie = new javax.swing.JComboBox<>();
        cbac = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuActualiza = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel27.setText("Causa del cambio:");

        jLabel10.setText("Adaptaciones curriculares:");

        jLabel28.setText("Problemas de aprendizaje:");

        jLabel11.setText("Grado de adaptación:");

        jLabel29.setText("Evaluación psicológica:");

        jLabel30.setText("Recibe tratamiento:");

        jLabel21.setText("Edad EGB 1:");

        jLabel22.setText("Perdida de curso:");

        jLabel8.setText("Relación con el grupo:");

        jLabel23.setText("Causa de la pérdida:");

        jLabel20.setText("Asignación de Paciente");

        jLabel12.setText("Especificar asignaturas:");

        jLabel19.setText("EGB 1:");

        jLabel24.setText("Deserción escolar:");

        jLabel13.setText("CDI:");

        jLabel31.setText("Aprovechamiento general:");

        jLabel14.setText("CDI edad:");

        jLabel32.setText("Actividad escolar:");

        jLabel25.setText("Causa de la deserción:");

        txtNombrePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePacienteActionPerformed(evt);
            }
        });

        jLabel15.setText("Inicial 1:");

        jLabel16.setText("Edad inicial 1:");

        jLabel17.setText("Inicial 2:");

        jLabel18.setText("Edad inicial 2:");

        jLabel1.setText("Id del paciente:");

        jLabel2.setText("Nombre del paciente:");

        jLabel3.setText("Cedula del paciente:");

        jLabel4.setText("Asignaturas preferidas:");

        jLabel5.setText("Asignaturas que disgustan:");

        jLabel6.setText("Relación con el docente:");

        jLabel7.setText("Le gusta ir a la institucion:");

        jLabel39.setText("Id del Especialista:");

        jLabel26.setText("Cambio de institución:");

        jLabel9.setText("Inclusión educativa:");

        cbcdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));

        cbini1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));

        cbini2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));

        cbebg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));

        cbpdc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));

        cbde.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));

        cbci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));

        cbpa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));

        cbep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));

        cbrt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));

        cbag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Malo", "Regular", "Deficiente" }));

        cbrd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Malo", "Regular", "Deficiente" }));

        cbli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Malo", "Regular", "Deficiente" }));

        cbrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Malo", "Regular", "Deficiente" }));

        cbie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));

        cbac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));

        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        menuActualiza.setText("Actualizar");
        menuActualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActualizaActionPerformed(evt);
            }
        });
        menu.add(menuActualiza);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEdadInicial1)
                                        .addComponent(txtCDIedad)
                                        .addComponent(txtEspecificarAsignaturas)
                                        .addComponent(txtGradoAdaptacion)
                                        .addComponent(txtAsignaturasDisgustan)
                                        .addComponent(txtAsignaturasPreferidas)
                                        .addComponent(txtCedulaPaciente)
                                        .addComponent(txtNombrePaciente)
                                        .addComponent(txtIdPaciente)
                                        .addComponent(cbcdi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbini1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbrd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbrg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cbac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel32))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdEspecialista, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                                    .addComponent(txtActividadEscolar)))
                            .addComponent(jLabel27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addGap(24, 24, 24)
                                    .addComponent(cbpa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel29)
                                        .addComponent(jLabel30)
                                        .addComponent(jLabel31)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(22, 22, 22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtEdadInicial2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCausaCambio, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCausaDesercion, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCausaPerdida, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEdadEGB1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbebg1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbini2, javax.swing.GroupLayout.Alignment.LEADING, 0, 280, Short.MAX_VALUE)
                                        .addComponent(cbpdc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbde, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbci, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbep, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbrt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbag, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel17)
                    .addComponent(cbini2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtEdadInicial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(cbebg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAsignaturasPreferidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtEdadEGB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAsignaturasDisgustan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(cbpdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel23)
                    .addComponent(txtCausaPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel24)
                    .addComponent(cbde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel25)
                    .addComponent(txtCausaDesercion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel26)
                    .addComponent(cbci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel27)
                    .addComponent(txtCausaCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGradoAdaptacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel28)
                    .addComponent(cbpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEspecificarAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(cbep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel13)
                    .addComponent(cbcdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCDIedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(cbag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel32)
                    .addComponent(txtActividadEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbini1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtEdadInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(txtIdEspecialista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static final String url="jdbc:mysql://localhost:3306/udipsai";
    public static final String usuario="root";
    public static final String contrasena="";   //Preguntar
    PreparedStatement ps;
    ResultSet rs;
    public Connection conexion() throws SQLException {
         Connection con= null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection)DriverManager.getConnection(url, usuario, contrasena);

        } catch (ClassNotFoundException e) {
            System.out.println(e);
        }

        return con;
    }
    
    
    private void cargarDatosPsicologiaClinica() {
    Connection con = null;

    try {
        con = conexion();

        PreparedStatement ps = con.prepareStatement("SELECT * FROM historia_psicologia_educativa WHERE idPaciente=?");
        ps.setString(1, Integer.toString(paciente.id));

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            txtIdPaciente.setText(String.valueOf(rs.getInt("idPaciente")));
            txtNombrePaciente.setText(rs.getString("nombre"));
            txtCedulaPaciente.setText(rs.getString("ci"));
            txtAsignaturasPreferidas.setText(rs.getString("asignaturasPreferidas"));
            txtAsignaturasDisgustan.setText(rs.getString("asignaturasDisgustan"));
            cbrd.setSelectedItem(rs.getString("relacionDocente"));
            cbcdi.setSelectedItem(rs.getString("cdi"));
            cbini1.setSelectedItem(rs.getString(" inicial1"));
            cbini2.setSelectedItem(rs.getString("inicial2"));
            cbli.setSelectedItem(rs.getString("leGustaEscuela"));
            cbrg.setSelectedItem(rs.getString(" relacionGrupo"));
            cbie.setSelectedItem(rs.getString("inclusionEducativa"));
            cbac.setSelectedItem(rs.getString("adaptacionesCurriculares"));
            txtGradoAdaptacion.setText(rs.getString("gradoAdaptacion"));
            txtEspecificarAsignaturas.setText(rs.getString("especificarAsignaturas"));
            txtCDIedad.setText(rs.getString("cdiEdad"));
            txtEdadInicial1.setText(rs.getString("edadInicial1"));
            txtEdadInicial2.setText(rs.getString("edadInicial2"));
            cbebg1.setSelectedItem(rs.getString("egb1"));
            txtEdadEGB1.setText(rs.getString("edadEGB1"));
            cbpdc.setSelectedItem(rs.getString("perdidaCurso"));
            txtCausaPerdida.setText(rs.getString("causaPerdida"));
            cbde.setSelectedItem(rs.getString("desercionEscolar"));
            txtCausaDesercion.setText(rs.getString("causaDesercion"));
            cbci.setSelectedItem(rs.getString("cambioInstitucion"));
            txtCausaCambio.setText(rs.getString("causaCambio"));
            cbpa.setSelectedItem(rs.getString("problemasAprendizajee"));
            cbep.setSelectedItem(rs.getString("evaluacionPsicologica"));
            cbrt.setSelectedItem(rs.getString("recibeTratamiento"));
            cbag.setSelectedItem(rs.getString("aprovechamientoGeneral"));
            txtActividadEscolar.setText(rs.getString("actividadEscolar"));
            txtIdEspecialista.setText(rs.getString("idEspecialista"));

        } else {
            JOptionPane.showMessageDialog(null, "No existe un paciente con ese número de cédula/ficha");
        }
    } catch (SQLException ex) {
        Logger.getLogger(Asignar_Paciente.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    private void menuActualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizaActionPerformed
        // TODO add your handling code here:

        try {
            Connection con = conexion(); // Obtener la conexión a la base de datos

            // Crear la consulta SQL para actualizar los datos en la tabla correspondiente
            String query = "UPDATE historia_psicologia_educativa SET nombre=?, ci=?, asignaturasPreferidas=?, asignaturasDisgustan=?, relacionDocente=?, leGustaEscuela=?, relacionGrupo=?, inclusionEducativa=?, adaptacionesCurriculares=?, gradoAdaptacion=?, especificarAsignaturas=?, cdi=?, cdiEdad=?, inicial1=?, edadInicial1=?, inicial2=?, edadInicial2=?, egb1=?, edadEGB1=?, perdidaCurso=?, causaPerdida=?, desercionEscolar=?, causaDesercion=?, cambioInstitucion=?, causaCambio=?, problemasAprendizaje=?, evaluacionPsicologica=?, recibeTratamiento=?, aprovechamientoGeneral=?, actividadEscolar=?, idEspecialista=? WHERE idPaciente=?";

            // Crear el objeto PreparedStatement para ejecutar la consulta
            PreparedStatement ps = con.prepareStatement(query);

            // Establecer los valores de los parámetros en la consulta
            ps.setString(1, txtNombrePaciente.getText());
            ps.setString(2, txtCedulaPaciente.getText());
            ps.setString(3, txtAsignaturasPreferidas.getText());
            ps.setString(4, txtAsignaturasDisgustan.getText());
            ps.setString(5, cbrd.getSelectedItem() != null ? cbrd.getSelectedItem().toString() : null);
            ps.setString(6, cbli.getSelectedItem() != null ? cbli.getSelectedItem().toString() : null);
            ps.setString(6, cbrg.getSelectedItem() != null ? cbrg.getSelectedItem().toString() : null);
            ps.setString(6, cbie.getSelectedItem() != null ? cbie.getSelectedItem().toString() : null);
            ps.setString(6, cbac.getSelectedItem() != null ? cbac.getSelectedItem().toString() : null);
            ps.setString(14, txtGradoAdaptacion.getText());
            ps.setString(14, txtEspecificarAsignaturas.getText());
            ps.setString(6, cbcdi.getSelectedItem() != null ? cbcdi.getSelectedItem().toString() : null);
            ps.setString(14, txtCDIedad.getText());
            ps.setString(7, cbini1.getSelectedItem() != null ? cbini1.getSelectedItem().toString() : null);
            ps.setString(14, txtEdadInicial1.getText());
            ps.setString(8, cbini2.getSelectedItem() != null ? cbini2.getSelectedItem().toString() : null);
            ps.setString(14, txtEdadInicial2.getText());
            ps.setString(9, cbebg1.getSelectedItem() != null ? cbebg1.getSelectedItem().toString() : null);
            ps.setString(14, txtEdadEGB1.getText());
            ps.setString(10, cbpdc.getSelectedItem() != null ? cbpdc.getSelectedItem().toString() : null);
            ps.setString(14, txtCausaPerdida.getText());
            ps.setString(11, cbde.getSelectedItem() != null ? cbde.getSelectedItem().toString() : null);
            ps.setString(14, txtCausaDesercion.getText());
            ps.setString(12, cbci.getSelectedItem() != null ? cbci.getSelectedItem().toString() : null);
            ps.setString(14, txtCausaCambio.getText());
            ps.setString(13, cbpa.getSelectedItem() != null ? cbpa.getSelectedItem().toString() : null);
            ps.setString(13, cbep.getSelectedItem() != null ? cbep.getSelectedItem().toString() : null);
            ps.setString(13, cbrt.getSelectedItem() != null ? cbrt.getSelectedItem().toString() : null);
            ps.setString(13, cbag.getSelectedItem() != null ? cbag.getSelectedItem().toString() : null);
            ps.setString(14, txtActividadEscolar.getText());
            ps.setString(38, txtIdPaciente.getText());

            // Ejecutar la consulta
            ps.executeUpdate();

            // Cerrar la conexión y liberar recursos
            ps.close();
            con.close();

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(this, "Los datos se han actualizado correctamente en la base de datos.");

        } catch (SQLException e) {
            // Manejar cualquier error de la base de datos
            JOptionPane.showMessageDialog(this, "Error al actualizar los datos en la base de datos: " + e.getMessage());
        }
    }//GEN-LAST:event_menuActualizaActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void txtNombrePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePacienteActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(PiscologiaEducativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(PiscologiaEducativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(PiscologiaEducativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(PiscologiaEducativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Paciente paciente = new Paciente(); // Aquí debes crear un objeto Paciente con los datos necesarios
            PiscologiaEducativa psicologiaClinica = new PiscologiaEducativa(paciente);
            psicologiaClinica.setVisible(true);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbac;
    private javax.swing.JComboBox<String> cbag;
    private javax.swing.JComboBox<String> cbcdi;
    private javax.swing.JComboBox<String> cbci;
    private javax.swing.JComboBox<String> cbde;
    private javax.swing.JComboBox<String> cbebg1;
    private javax.swing.JComboBox<String> cbep;
    private javax.swing.JComboBox<String> cbie;
    private javax.swing.JComboBox<String> cbini1;
    private javax.swing.JComboBox<String> cbini2;
    private javax.swing.JComboBox<String> cbli;
    private javax.swing.JComboBox<String> cbpa;
    private javax.swing.JComboBox<String> cbpdc;
    private javax.swing.JComboBox<String> cbrd;
    private javax.swing.JComboBox<String> cbrg;
    private javax.swing.JComboBox<String> cbrt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menuActualiza;
    private javax.swing.JTextField txtActividadEscolar;
    private javax.swing.JTextField txtAsignaturasDisgustan;
    private javax.swing.JTextField txtAsignaturasPreferidas;
    private javax.swing.JTextField txtCDIedad;
    private javax.swing.JTextField txtCausaCambio;
    private javax.swing.JTextField txtCausaDesercion;
    private javax.swing.JTextField txtCausaPerdida;
    private javax.swing.JTextField txtCedulaPaciente;
    private javax.swing.JTextField txtEdadEGB1;
    private javax.swing.JTextField txtEdadInicial1;
    private javax.swing.JTextField txtEdadInicial2;
    private javax.swing.JTextField txtEspecificarAsignaturas;
    private javax.swing.JTextField txtGradoAdaptacion;
    private javax.swing.JTextField txtIdEspecialista;
    private javax.swing.JTextField txtIdPaciente;
    private javax.swing.JTextField txtNombrePaciente;
    // End of variables declaration//GEN-END:variables
}
