/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author User
 */
public class DesarrolloIntegralDelPacienteBuscar extends javax.swing.JInternalFrame {

    /**
     * Creates new form DesarrolloIntegralDelPacienteBuscar
     */
    public DesarrolloIntegralDelPacienteBuscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField17 = new javax.swing.JTextField();
        escritorioIntegralBuscar = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jTextField17.setText("jTextField17");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Embarazo deseado:");

        jLabel2.setText("Control de em,barazo: ");

        jLabel3.setText("Enfermedades de la madre: ");

        jLabel4.setText("Consumo de medicamenmtos o sustancias: ");

        jLabel5.setText("Amenaza de aborto:");

        jLabel6.setText("Estado emocional: ");

        jLabel7.setText("Nacimiento del paciente: ");

        jLabel8.setText("Duracion del embarazo:");

        jLabel9.setText("Tipo de parto: ");

        jLabel10.setText("lloro al nacer: ");

        jLabel11.setText("Peso: ");

        jLabel12.setText("Talla: ");

        jLabel13.setText("Mal formacion congenita: ");

        jLabel14.setText("Problemas de alimentacion: ");

        jLabel15.setText("Complicaciones en el parto: ");

        jLabel16.setText("Incubadora: ");

        jLabel17.setText("Tiempo: ");

        jLabel18.setText("Causa: ");

        jLabel19.setText("Esquema de  vacunacion completo: ");

        jLabel20.setText("Control cefalico: ");

        jLabel21.setText("Sedestacion: ");

        jLabel22.setText("Bipedestacion: ");

        jLabel23.setText("Camina con apoyo: ");

        jLabel24.setText("Camina solo: ");

        jLabel25.setText("Sube escaleras: ");

        jLabel26.setText("Control de esfinteres: ");

        jLabel27.setText("Balbuceo: ");

        jLabel28.setText("Vocalizacion: ");

        jLabel29.setText("Juego vocal: ");

        jLabel30.setText("Silabeo: ");

        jLabel31.setText("Primeras palabras: ");

        jLabel32.setText("Oraciones: ");

        jLabel33.setText("Formacion linguistica completa: ");

        jLabel34.setText("Numero total de palabras:");

        jLabel35.setText("Especialista: ");

        escritorioIntegralBuscar.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jLabel35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorioIntegralBuscar.setLayer(jTextField36, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioIntegralBuscarLayout = new javax.swing.GroupLayout(escritorioIntegralBuscar);
        escritorioIntegralBuscar.setLayout(escritorioIntegralBuscarLayout);
        escritorioIntegralBuscarLayout.setHorizontalGroup(
            escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioIntegralBuscarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(escritorioIntegralBuscarLayout.createSequentialGroup()
                            .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(97, 97, 97)
                            .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(jTextField2)
                                .addComponent(jTextField3)))
                        .addGroup(escritorioIntegralBuscarLayout.createSequentialGroup()
                            .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(18, 18, 18)
                            .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(jTextField5)
                                .addComponent(jTextField6)
                                .addComponent(jTextField7)
                                .addComponent(jTextField8)
                                .addComponent(jTextField9)
                                .addComponent(jTextField10)
                                .addComponent(jTextField11)
                                .addComponent(jTextField12)
                                .addComponent(jTextField13))))
                    .addGroup(escritorioIntegralBuscarLayout.createSequentialGroup()
                        .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(escritorioIntegralBuscarLayout.createSequentialGroup()
                                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField18)
                                    .addComponent(jTextField19, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addGap(12, 12, 12))
                            .addGroup(escritorioIntegralBuscarLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(23, 23, 23)
                        .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField15)
                            .addComponent(jTextField20, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addGap(26, 26, 26)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioIntegralBuscarLayout.createSequentialGroup()
                        .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField16)
                            .addComponent(jTextField21)
                            .addComponent(jTextField22, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(escritorioIntegralBuscarLayout.createSequentialGroup()
                        .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(escritorioIntegralBuscarLayout.createSequentialGroup()
                                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField23, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jTextField24)
                                    .addComponent(jTextField25)
                                    .addComponent(jTextField26)
                                    .addComponent(jTextField27)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, escritorioIntegralBuscarLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField28, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(jTextField29)))
                            .addGroup(escritorioIntegralBuscarLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(131, 131, 131)
                                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField34)
                                    .addComponent(jTextField33)
                                    .addComponent(jTextField35)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, escritorioIntegralBuscarLayout.createSequentialGroup()
                                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(escritorioIntegralBuscarLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(132, 132, 132))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioIntegralBuscarLayout.createSequentialGroup()
                                        .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel35)
                                            .addComponent(jLabel14))
                                        .addGap(52, 52, 52)))
                                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField30)
                                    .addComponent(jTextField32)
                                    .addComponent(jTextField36)
                                    .addComponent(jTextField31))))
                        .addGap(15, 15, 15))))
        );
        escritorioIntegralBuscarLayout.setVerticalGroup(
            escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioIntegralBuscarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel16)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel18)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel19)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel20)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel21)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel22)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel25)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel24)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30)
                    .addComponent(jLabel34)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioIntegralBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel27)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenuItem1.setText("Regresar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Editar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorioIntegralBuscar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorioIntegralBuscar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        DesarrolloIntegralDelPaciente integral = new DesarrolloIntegralDelPaciente();
        escritorioIntegralBuscar.add(integral);
        integral.show();
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorioIntegralBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
