/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asignaciones;

import comons.datos.mysql;
import configReader.ConfigReader;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maria Mercedes Encalada Arévalo
 */
public class Asignar_Paciente extends javax.swing.JFrame {
    ConfigReader configReader = new ConfigReader();
    public String url = "jdbc:mysql://"+configReader.getIp()+":3306/"+configReader.getDatabase();
    public String usuario = configReader.getUser();
    public String contrasena = configReader.getPass();//Preguntar
    PreparedStatement ps;
    ResultSet rs;

    public Connection conexion() throws SQLException {
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(url, usuario, contrasena);

        } catch (ClassNotFoundException e) {
            System.out.println(e);
        }

        return con;
    }

    public Asignar_Paciente() {
        initComponents();
        /**
         * try { Class.forName("com.mysql.jdbc.Driver");
         *
         * } catch (ClassNotFoundException ex) {
         * Logger.getLogger(Asignar_Paciente.class.getName()).log(Level.SEVERE,null,ex);
         * }
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cedulaesp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_nomesp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_areaesp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cedfich = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_ficha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_nomapepac = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn1_busesp = new javax.swing.JButton();
        txt_apeesp = new javax.swing.JTextField();
        txt_cedpac = new javax.swing.JTextField();
        btn2_buspac = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        Guardar = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(181, 37, 26));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Asignar Paciente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel3.setText("Cédula del especialista:");

        jLabel4.setText("Nombre del Especialista:");

        txt_nomesp.setEditable(false);

        jLabel5.setText("Área:");

        txt_areaesp.setEditable(false);

        jLabel6.setText("Cédula o # de ficha del paciente:");

        jLabel7.setText("# de ficha del paciente:");

        txt_ficha.setEditable(false);

        jLabel8.setText("Nombre Completo del  Paciente:");

        txt_nomapepac.setEditable(false);

        jLabel9.setText("Cédula de Identidad:");

        btn1_busesp.setBackground(new java.awt.Color(181, 37, 26));
        btn1_busesp.setText("Buscar");
        btn1_busesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_busespActionPerformed(evt);
            }
        });

        txt_apeesp.setEditable(false);
        txt_apeesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apeespActionPerformed(evt);
            }
        });

        txt_cedpac.setEditable(false);

        btn2_buspac.setBackground(new java.awt.Color(181, 37, 26));
        btn2_buspac.setText("Buscar");
        btn2_buspac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2_buspacActionPerformed(evt);
            }
        });

        jLabel11.setText("Apellido del Especialista:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ficha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nomapepac, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_cedfich, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn2_buspac, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cedpac, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(77, 77, 77)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_areaesp)
                                        .addComponent(txt_apeesp, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_nomesp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(128, 128, 128))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_cedulaesp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn1_busesp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cedulaesp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_busesp)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nomesp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apeesp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_areaesp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cedfich, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2_buspac)
                            .addComponent(jLabel6))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ficha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nomapepac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_cedpac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        menu.setText("Asignar");

        Guardar.setText("Guardar Asignación");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        menu.add(Guardar);

        jMenuBar2.add(menu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1_busespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_busespActionPerformed

        Connection con = null;
        try {
            con = conexion();
            //Preparo una consulta:vamos a buscar por cedula
            ps = con.prepareStatement("select * from especialista inner join especialidad on  especialista.id_especialidad=especialidad.id where cedula=?");
            ps.setString(1, txt_cedulaesp.getText());
            //traiga Resultados de la consulta
            rs = ps.executeQuery();

            if (rs.next()) {
                txt_nomesp.setText(rs.getString("primerNombre"));
                txt_apeesp.setText(rs.getString("primerApellido"));
                txt_areaesp.setText(rs.getString("area"));
            } else {
                JOptionPane.showMessageDialog(null, "No existe un especialista con ese número de cédula");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Asignar_Paciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn1_busespActionPerformed

    private void txt_apeespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apeespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apeespActionPerformed

    private void btn2_buspacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2_buspacActionPerformed
        Connection con = null;
        try {
            con = conexion();
            //Preparo una consulta:vamos a buscar por cedula
            ps = con.prepareStatement("select * from paciente where cedula=? or id=?");
            ps.setString(1, txt_cedfich.getText());
            ps.setString(2, txt_cedfich.getText());
            //traiga Resultados de la consulta
            rs = ps.executeQuery();

            if (rs.next()) {
                //txt_ficha.setText(Integer.toString(rs.getInt("id")));
                txt_ficha.setText(rs.getString("id"));
                txt_nomapepac.setText(rs.getString("nombresApellidos"));
                txt_cedpac.setText(rs.getString("cedula"));
            } else {
                JOptionPane.showMessageDialog(null, "No existe un paciente con ese número de cédula/ficha");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Asignar_Paciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn2_buspacActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        try {
            // Verificar si los campos están llenos
            String ficha = txt_ficha.getText();
            String cedulaEsp = txt_cedulaesp.getText();

            if (ficha.isEmpty() || cedulaEsp.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            } else {
                Connection con = null;
                try {
                    con = conexion();

                    // Preparar la consulta de inserción
                    ps = con.prepareStatement("INSERT INTO asignaciones (idPaciente, cedulaEspecialista) VALUES (?, ?)");
                    ps.setString(1, ficha);
                    ps.setString(2, cedulaEsp);

                    int res = ps.executeUpdate();

                    // Verificar el resultado de la ejecución
                    if (res > 0) {
                        JOptionPane.showMessageDialog(null, "Los datos fueron guardados correctamente");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al guardar los datos");
                    }
                    // Verificar si es especialista o pasante
                    PreparedStatement psEsp = con.prepareStatement("SELECT esPasante, especialistaAsignado FROM especialista WHERE cedula = ?");
                    psEsp.setString(1, cedulaEsp);
                    ResultSet rsEsp = psEsp.executeQuery();
                    if (rsEsp.next()) {
                        String esPasante = rsEsp.getString("esPasante");
                        if (esPasante.equals("true")) {
                            String especialistaAsignado=rsEsp.getString("especialistaAsignado");

                            // Asignar el especialista al paciente
                            ps = con.prepareStatement("INSERT INTO asignaciones (idPaciente, cedulaEspecialista) VALUES (?, ?)");
                            ps.setString(1, ficha);
                            ps.setString(2, especialistaAsignado);
                            res = ps.executeUpdate();
                            // Verificar el resultado de la ejecución
                            if (res > 0) {
                                JOptionPane.showMessageDialog(null, "El especialista fue correctamente asignado al especialista asignado al pasante");
                            } else {
                                JOptionPane.showMessageDialog(null, "Error al asignar un especialista al pasante con un paciente");
                            }
                        }
                    }

                    con.close();
                } catch (SQLException ex) {
                    System.out.println(ex);
                    JOptionPane.showMessageDialog(null, "Error al guardar los datos");
                }
            }
        } catch (HeadlessException ex) {
            
            JOptionPane.showMessageDialog(null, "Error al guardar los datos");
        }
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asignar_Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JButton btn1_busesp;
    private javax.swing.JButton btn2_buspac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menu;
    private javax.swing.JTextField txt_apeesp;
    private javax.swing.JTextField txt_areaesp;
    private javax.swing.JTextField txt_cedfich;
    private javax.swing.JTextField txt_cedpac;
    private javax.swing.JTextField txt_cedulaesp;
    private javax.swing.JTextField txt_ficha;
    private javax.swing.JTextField txt_nomapepac;
    private javax.swing.JTextField txt_nomesp;
    // End of variables declaration//GEN-END:variables
}
